service: mastere-ramda
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  profile: serverless-admin
  region: ap-northeast-2

functions:
  hello:
    handler: app.hello
  test:
    handler: app.test
